# Generated by Django 4.2.21 on 2025-05-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='select_task',
            field=models.BooleanField(default=False, help_text='Select this task for actions'),
        ),
    ]
