# Generated by Django 4.2.21 on 2025-05-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_select_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='select_task',
        ),
    ]
